### ISSUE TITLE
Add a CI

### ISSUE THREAD

**Issue by JJTech0130** [rileytestut/AltServer-Windows#21]
It would be cool if you could setup a CI (appveyor, etc.) to automatically build new commits. I’m trying to set one up in my fork, but I don’t have much experience with Visual Studio projects.

**Comment by JJTech0130** [comment]
Working on the AppVeyor configuration, this is about as far as I've gotten:
```yaml
version: 1.5.0-b{build}
clone_depth: 1
install:
- ps: >-
    git submodule update -q --init

    vcpkg install cpprestsdk dirent mdnsresponder
cache: c:\tools\vcpkg\installed\
build: off
```
